"""
    Fanlens API

     Fanlens API to handle \"activities\". Predictions are performed automatically and can be managed here ## Concepts The API consists of 4 main concepts: sources, activities and tags (bundled in tagsets) and models used for predictions. * An activity is a text based action performed by a user, e.g. a Facebook Comment or a Tweet. * A source is the originator of these activities and is used for importing. Currently Facebook, Twitter, and Generic Sources are supported. * A tag is a piece of meta information that is used to build specialized speech models, e.g. \"positive\", or \"negative\". They are bundled in tagsets for convenience, e.g. \"Emotion\".

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import unittest
from typing import Type

from client.apis.tags_api import TagsApi
from test import ApiTestCase


class TestTagsApi(ApiTestCase[TagsApi]):
    """ TagsApi unit test stubs """

    @property
    def api_class(self) -> Type[TagsApi]:
        return TagsApi

    def test_tags_get(self) -> None:
        """
        Test case for tags_get

        Get all tags of current user
        """
        self.fail()

    def test_tags_tag_delete(self) -> None:
        """
        Test case for tags_tag_delete

        Remove tag and all it's associations from the system
        """
        self.fail()

    def test_tags_tag_get(self) -> None:
        """
        Test case for tags_tag_get

        Get this tag
        """
        self.fail()

    def test_tags_tag_put(self) -> None:
        """
        Test case for tags_tag_put

        Add tag to the system
        """
        self.fail()


if __name__ == '__main__':
    unittest.main()
