"""
    Fanlens API

     Fanlens API to handle \"activities\". Predictions are performed automatically and can be managed here ## Concepts The API consists of 4 main concepts: sources, activities and tags (bundled in tagsets) and models used for predictions. * An activity is a text based action performed by a user, e.g. a Facebook Comment or a Tweet. * A source is the originator of these activities and is used for importing. Currently Facebook, Twitter, and Generic Sources are supported. * A tag is a piece of meta information that is used to build specialized speech models, e.g. \"positive\", or \"negative\". They are bundled in tagsets for convenience, e.g. \"Emotion\".

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import unittest
from typing import Type

from client.apis.tagsets_api import TagsetsApi
from test import ApiTestCase


class TestTagsetsApi(ApiTestCase[TagsetsApi]):
    """ TagsetsApi unit test stubs """

    @property
    def api_class(self) -> Type[TagsetsApi]:
        return TagsetsApi

    def test_tagsets_get(self) -> None:
        """
        Test case for tagsets_get

        Get tagsets of current user
        """
        self.fail()

    def test_tagsets_post(self) -> None:
        """
        Test case for tagsets_post

        Create new tagset
        """
        self.fail()

    def test_tagsets_tagset_id_delete(self) -> None:
        """
        Test case for tagsets_tagset_id_delete

        Remove the tagset
        """
        self.fail()

    def test_tagsets_tagset_id_get(self) -> None:
        """
        Test case for tagsets_tagset_id_get

        Get tagset
        """
        self.fail()

    def test_tagsets_tagset_id_patch(self) -> None:
        """
        Test case for tagsets_tagset_id_patch

        Update the tagset
        """
        self.fail()

    def test_tagsets_tagset_id_tag_delete(self) -> None:
        """
        Test case for tagsets_tagset_id_tag_delete

        Remove tag from tagset
        """
        self.fail()

    def test_tagsets_tagset_id_tag_put(self) -> None:
        """
        Test case for tagsets_tagset_id_tag_put

        Add tag to the tagset
        """
        self.fail()


if __name__ == '__main__':
    unittest.main()
