# coding: utf-8

"""
    Fanlens API

     Fanlens API to handle \"activities\". Predictions are performed automatically and can be managed here ## Concepts The API consists of 4 main concepts: sources, activities and tags (bundled in tagsets) and models used for predictions. * An activity is a text based action performed by a user, e.g. a Facebook Comment or a Tweet. * A source is the originator of these activities and is used for importing. Currently Facebook, Twitter, and Generic Sources are supported. * A tag is a piece of meta information that is used to build specialized speech models, e.g. \"positive\", or \"negative\". They are bundled in tagsets for convenience, e.g. \"Emotion\".

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.sources_api import SourcesApi


class TestSourcesApi(unittest.TestCase):
    """ SourcesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.sources_api.SourcesApi()

    def tearDown(self):
        pass

    def test_sources_get(self):
        """
        Test case for sources_get

        Get sources of current user
        """
        pass

    def test_sources_post(self):
        """
        Test case for sources_post

        Create a new Source
        """
        pass

    def test_sources_source_id_delete(self):
        """
        Test case for sources_source_id_delete

        Remove the source, **WARNING!** This will remove all data associated with the source!
        """
        pass

    def test_sources_source_id_get(self):
        """
        Test case for sources_source_id_get

        Get source
        """
        pass

    def test_sources_source_id_patch(self):
        """
        Test case for sources_source_id_patch

        Update the source.
        """
        pass


if __name__ == '__main__':
    unittest.main()
