"""
    Fanlens API

     Fanlens API to handle \"activities\". Predictions are performed automatically and can be managed here ## Concepts The API consists of 4 main concepts: sources, activities and tags (bundled in tagsets) and models used for predictions. * An activity is a text based action performed by a user, e.g. a Facebook Comment or a Tweet. * A source is the originator of these activities and is used for importing. Currently Facebook, Twitter, and Generic Sources are supported. * A tag is a piece of meta information that is used to build specialized speech models, e.g. \"positive\", or \"negative\". They are bundled in tagsets for convenience, e.g. \"Emotion\".

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import unittest
from typing import Type

from client.apis.import_api import ImportApi
from test import ApiTestCase


class TestImportApi(ApiTestCase[ImportApi]):
    """ ImportApi unit test stubs """

    @property
    def api_class(self) -> Type[ImportApi]:
        return ImportApi

    def test_root_post(self) -> None:
        """
        Test case for root_post

        Import a bulk of activities
        """
        self.fail()

    def test_source_id_activity_id_delete(self) -> None:
        """
        Test case for source_id_activity_id_delete

        Delete this activity
        """
        self.fail()

    def test_source_id_activity_id_put(self) -> None:
        """
        Test case for source_id_activity_id_put

        Create or update this activity
        """
        self.fail()


if __name__ == '__main__':
    unittest.main()
