# coding: utf-8

"""
    Fanlens API

     Fanlens API to handle \"activities\". Predictions are performed automatically and can be managed here ## Concepts The API consists of 4 main concepts: sources, activities and tags (bundled in tagsets) and models used for predictions. * An activity is a text based action performed by a user, e.g. a Facebook Comment or a Tweet. * A source is the originator of these activities and is used for importing. Currently Facebook, Twitter, and Generic Sources are supported. * A tag is a piece of meta information that is used to build specialized speech models, e.g. \"positive\", or \"negative\". They are bundled in tagsets for convenience, e.g. \"Emotion\".

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .activity import Activity
from .activity_list import ActivityList
from .error import Error
from .import_list import ImportList
from .job import Job
from .model import Model
from .model_import import ModelImport
from .model_list import ModelList
from .model_query import ModelQuery
from .model_train_job import ModelTrainJob
from .ok import Ok
from .prediction import Prediction
from .single_tag_info import SingleTagInfo
from .source import Source
from .sources_list import SourcesList
from .tag import Tag
from .tag_change_set import TagChangeSet
from .tag_counts import TagCounts
from .tag_info import TagInfo
from .tag_set import TagSet
from .tag_set_list import TagSetList
from .tags import Tags
from .text_prediction import TextPrediction
from .text_prediction_query import TextPredictionQuery
from .user import User
