# coding: utf-8

"""
    Fanlens API

     Fanlens API to handle \"activities\". Predictions are performed automatically and can be managed here ## Concepts The API consists of 4 main concepts: sources, activities and tags (bundled in tagsets) and models used for predictions. * An activity is a text based action performed by a user, e.g. a Facebook Comment or a Tweet. * A source is the originator of these activities and is used for importing. Currently Facebook, Twitter, and Generic Sources are supported. * A tag is a piece of meta information that is used to build specialized speech models, e.g. \"positive\", or \"negative\". They are bundled in tagsets for convenience, e.g. \"Emotion\".

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class ActivityApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def root_get(self, **kwargs):
        """
        Get a list of activities.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.root_get(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param list[int] source_ids:
        :param list[int] tagset_ids:
        :param list[str] tags:
        :param list[str] languages: Inferred language of text
        :param int count: number of activities to fetch
        :param str max_id: used for cursoring
        :param datetime since: DateTime of oldest entry
        :param datetime until: DateTime of newest entry
        :param bool random: should a random sample be drawn
        :return: ActivityList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.root_get_with_http_info(**kwargs)
        else:
            (data) = self.root_get_with_http_info(**kwargs)
            return data

    def root_get_with_http_info(self, **kwargs):
        """
        Get a list of activities.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.root_get_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param list[int] source_ids:
        :param list[int] tagset_ids:
        :param list[str] tags:
        :param list[str] languages: Inferred language of text
        :param int count: number of activities to fetch
        :param str max_id: used for cursoring
        :param datetime since: DateTime of oldest entry
        :param datetime until: DateTime of newest entry
        :param bool random: should a random sample be drawn
        :return: ActivityList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['source_ids', 'tagset_ids', 'tags', 'languages', 'count', 'max_id', 'since', 'until', 'random']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method root_get" % key
                )
            params[key] = val
        del params['kwargs']

        if 'source_ids' in params and len(params['source_ids']) > 10:
            raise ValueError("Invalid value for parameter `source_ids` when calling `root_get`, number of items must be less than or equal to `10`")
        if 'tagset_ids' in params and len(params['tagset_ids']) > 10:
            raise ValueError("Invalid value for parameter `tagset_ids` when calling `root_get`, number of items must be less than or equal to `10`")
        if 'tags' in params and len(params['tags']) > 30:
            raise ValueError("Invalid value for parameter `tags` when calling `root_get`, number of items must be less than or equal to `30`")
        if 'languages' in params and len(params['languages']) > 30:
            raise ValueError("Invalid value for parameter `languages` when calling `root_get`, number of items must be less than or equal to `30`")
        if 'count' in params and params['count'] > 500:
            raise ValueError("Invalid value for parameter `count` when calling `root_get`, must be a value less than or equal to `500`")
        if 'count' in params and params['count'] < 0:
            raise ValueError("Invalid value for parameter `count` when calling `root_get`, must be a value greater than or equal to `0`")
        if 'max_id' in params and len(params['max_id']) > 128:
            raise ValueError("Invalid value for parameter `max_id` when calling `root_get`, length must be less than or equal to `128`")
        if 'max_id' in params and len(params['max_id']) < 1:
            raise ValueError("Invalid value for parameter `max_id` when calling `root_get`, length must be greater than or equal to `1`")

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'source_ids' in params:
            query_params.append(('source_ids', params['source_ids']))
            collection_formats['source_ids'] = 'csv'
        if 'tagset_ids' in params:
            query_params.append(('tagset_ids', params['tagset_ids']))
            collection_formats['tagset_ids'] = 'csv'
        if 'tags' in params:
            query_params.append(('tags', params['tags']))
            collection_formats['tags'] = 'csv'
        if 'languages' in params:
            query_params.append(('languages', params['languages']))
            collection_formats['languages'] = 'csv'
        if 'count' in params:
            query_params.append(('count', params['count']))
        if 'max_id' in params:
            query_params.append(('max_id', params['max_id']))
        if 'since' in params:
            query_params.append(('since', params['since']))
        if 'until' in params:
            query_params.append(('until', params['until']))
        if 'random' in params:
            query_params.append(('random', params['random']))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['jwt']

        return self.api_client.call_api('/', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ActivityList',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def source_id_activity_id_delete(self, source_id, activity_id, **kwargs):
        """
        Delete this activity
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.source_id_activity_id_delete(source_id, activity_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int source_id: (required)
        :param str activity_id: (required)
        :return: Ok
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.source_id_activity_id_delete_with_http_info(source_id, activity_id, **kwargs)
        else:
            (data) = self.source_id_activity_id_delete_with_http_info(source_id, activity_id, **kwargs)
            return data

    def source_id_activity_id_delete_with_http_info(self, source_id, activity_id, **kwargs):
        """
        Delete this activity
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.source_id_activity_id_delete_with_http_info(source_id, activity_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int source_id: (required)
        :param str activity_id: (required)
        :return: Ok
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['source_id', 'activity_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method source_id_activity_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'source_id' is set
        if ('source_id' not in params) or (params['source_id'] is None):
            raise ValueError("Missing the required parameter `source_id` when calling `source_id_activity_id_delete`")
        # verify the required parameter 'activity_id' is set
        if ('activity_id' not in params) or (params['activity_id'] is None):
            raise ValueError("Missing the required parameter `activity_id` when calling `source_id_activity_id_delete`")

        if 'activity_id' in params and len(params['activity_id']) > 128:
            raise ValueError("Invalid value for parameter `activity_id` when calling `source_id_activity_id_delete`, length must be less than or equal to `128`")
        if 'activity_id' in params and len(params['activity_id']) < 1:
            raise ValueError("Invalid value for parameter `activity_id` when calling `source_id_activity_id_delete`, length must be greater than or equal to `1`")

        collection_formats = {}

        path_params = {}
        if 'source_id' in params:
            path_params['source_id'] = params['source_id']
        if 'activity_id' in params:
            path_params['activity_id'] = params['activity_id']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['jwt']

        return self.api_client.call_api('/{source_id}/{activity_id}', 'DELETE',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='Ok',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def source_id_activity_id_get(self, source_id, activity_id, **kwargs):
        """
        Get this activity
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.source_id_activity_id_get(source_id, activity_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int source_id: (required)
        :param str activity_id: (required)
        :return: Activity
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.source_id_activity_id_get_with_http_info(source_id, activity_id, **kwargs)
        else:
            (data) = self.source_id_activity_id_get_with_http_info(source_id, activity_id, **kwargs)
            return data

    def source_id_activity_id_get_with_http_info(self, source_id, activity_id, **kwargs):
        """
        Get this activity
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.source_id_activity_id_get_with_http_info(source_id, activity_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int source_id: (required)
        :param str activity_id: (required)
        :return: Activity
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['source_id', 'activity_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method source_id_activity_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'source_id' is set
        if ('source_id' not in params) or (params['source_id'] is None):
            raise ValueError("Missing the required parameter `source_id` when calling `source_id_activity_id_get`")
        # verify the required parameter 'activity_id' is set
        if ('activity_id' not in params) or (params['activity_id'] is None):
            raise ValueError("Missing the required parameter `activity_id` when calling `source_id_activity_id_get`")

        if 'activity_id' in params and len(params['activity_id']) > 128:
            raise ValueError("Invalid value for parameter `activity_id` when calling `source_id_activity_id_get`, length must be less than or equal to `128`")
        if 'activity_id' in params and len(params['activity_id']) < 1:
            raise ValueError("Invalid value for parameter `activity_id` when calling `source_id_activity_id_get`, length must be greater than or equal to `1`")

        collection_formats = {}

        path_params = {}
        if 'source_id' in params:
            path_params['source_id'] = params['source_id']
        if 'activity_id' in params:
            path_params['activity_id'] = params['activity_id']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['jwt']

        return self.api_client.call_api('/{source_id}/{activity_id}', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='Activity',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def source_id_activity_id_put(self, source_id, activity_id, activity_import, **kwargs):
        """
        Create or update this activity
        The data field format is source dependent
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.source_id_activity_id_put(source_id, activity_id, activity_import, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int source_id: (required)
        :param str activity_id: (required)
        :param ModelImport activity_import: (required)
        :return: Ok
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.source_id_activity_id_put_with_http_info(source_id, activity_id, activity_import, **kwargs)
        else:
            (data) = self.source_id_activity_id_put_with_http_info(source_id, activity_id, activity_import, **kwargs)
            return data

    def source_id_activity_id_put_with_http_info(self, source_id, activity_id, activity_import, **kwargs):
        """
        Create or update this activity
        The data field format is source dependent
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.source_id_activity_id_put_with_http_info(source_id, activity_id, activity_import, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int source_id: (required)
        :param str activity_id: (required)
        :param ModelImport activity_import: (required)
        :return: Ok
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['source_id', 'activity_id', 'activity_import']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method source_id_activity_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'source_id' is set
        if ('source_id' not in params) or (params['source_id'] is None):
            raise ValueError("Missing the required parameter `source_id` when calling `source_id_activity_id_put`")
        # verify the required parameter 'activity_id' is set
        if ('activity_id' not in params) or (params['activity_id'] is None):
            raise ValueError("Missing the required parameter `activity_id` when calling `source_id_activity_id_put`")
        # verify the required parameter 'activity_import' is set
        if ('activity_import' not in params) or (params['activity_import'] is None):
            raise ValueError("Missing the required parameter `activity_import` when calling `source_id_activity_id_put`")

        if 'activity_id' in params and len(params['activity_id']) > 128:
            raise ValueError("Invalid value for parameter `activity_id` when calling `source_id_activity_id_put`, length must be less than or equal to `128`")
        if 'activity_id' in params and len(params['activity_id']) < 1:
            raise ValueError("Invalid value for parameter `activity_id` when calling `source_id_activity_id_put`, length must be greater than or equal to `1`")

        collection_formats = {}

        path_params = {}
        if 'source_id' in params:
            path_params['source_id'] = params['source_id']
        if 'activity_id' in params:
            path_params['activity_id'] = params['activity_id']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'activity_import' in params:
            body_params = params['activity_import']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['jwt']

        return self.api_client.call_api('/{source_id}/{activity_id}', 'PUT',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='Ok',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def source_id_activity_id_tags_patch(self, source_id, activity_id, body, **kwargs):
        """
        Modify tags of activity
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.source_id_activity_id_tags_patch(source_id, activity_id, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int source_id: (required)
        :param str activity_id: (required)
        :param TagChangeSet body: (required)
        :return: Activity
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.source_id_activity_id_tags_patch_with_http_info(source_id, activity_id, body, **kwargs)
        else:
            (data) = self.source_id_activity_id_tags_patch_with_http_info(source_id, activity_id, body, **kwargs)
            return data

    def source_id_activity_id_tags_patch_with_http_info(self, source_id, activity_id, body, **kwargs):
        """
        Modify tags of activity
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.source_id_activity_id_tags_patch_with_http_info(source_id, activity_id, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int source_id: (required)
        :param str activity_id: (required)
        :param TagChangeSet body: (required)
        :return: Activity
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['source_id', 'activity_id', 'body']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method source_id_activity_id_tags_patch" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'source_id' is set
        if ('source_id' not in params) or (params['source_id'] is None):
            raise ValueError("Missing the required parameter `source_id` when calling `source_id_activity_id_tags_patch`")
        # verify the required parameter 'activity_id' is set
        if ('activity_id' not in params) or (params['activity_id'] is None):
            raise ValueError("Missing the required parameter `activity_id` when calling `source_id_activity_id_tags_patch`")
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `source_id_activity_id_tags_patch`")

        if 'activity_id' in params and len(params['activity_id']) > 128:
            raise ValueError("Invalid value for parameter `activity_id` when calling `source_id_activity_id_tags_patch`, length must be less than or equal to `128`")
        if 'activity_id' in params and len(params['activity_id']) < 1:
            raise ValueError("Invalid value for parameter `activity_id` when calling `source_id_activity_id_tags_patch`, length must be greater than or equal to `1`")

        collection_formats = {}

        path_params = {}
        if 'source_id' in params:
            path_params['source_id'] = params['source_id']
        if 'activity_id' in params:
            path_params['activity_id'] = params['activity_id']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['jwt']

        return self.api_client.call_api('/{source_id}/{activity_id}/tags', 'PATCH',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='Activity',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
